import { Component, AfterViewInit, ViewChild, ElementRef,OnInit } from 
'@angular/core';
import {ActivatedRoute} from '@angular/router' ;
declare const google: any;

interface Marker {
lat: number;
lng: number;
label?: string;
draggable?: boolean;
}
const data = {
    chart: {
      caption: "Power generated by Solar Farm",
      captionontop: "120 MegaWatt",
      origw: "380",
      origh: "250",
      gaugestartangle: "135",
      gaugeendangle: "45",
      gaugeoriginx: "190",
      gaugeoriginy: "220",
      gaugeouterradius: "190",
      theme: "candy",
      showvalue: "1",
      numbersuffix: " %",
      valuefontsize: "25"
    },
    colorrange: {
      color: [
        {
          minvalue: "0",
          maxvalue: "25",
          code: "	#ADD8E6"
        },
        {
          minvalue: "25",
          maxvalue: "50",
          code: "#62B58F "
        },
        {
          minvalue: "50",
          maxvalue: "75",
          code: "#FFC533 "
        }
        , {
            minvalue: "75",
            maxvalue: "100",
            code: "#F2726F"
          }
      ]
    },
    dials: {
      dial: [
        {
          value: "0.3",
          tooltext: "Moderate Pressure"
        }
      ]
    }
  };
@Component({
  selector: 'app-solarPowerPlant',
  templateUrl: './solarPowerPlant.component.html',
  styleUrls: ['./solarPowerPlant.component.css']
})
export class SolarPowerPlantComponent implements OnInit {
  
  solarPowerPlant
  width = 450;
  height = 400;
  type = "angulargauge";
  dataFormat = "json";
  dataSource = data;
  urlID ;
  constructor(private route : ActivatedRoute ) 
{    
    this.route.params.subscribe(params =>{

        console.log(params['id']) ;
        this.urlID= params['id'] ;
    }) 
}


  ngOnInit() {

    
    this.solarPowerPlant =[
        { 
          id : 0 ,
          lat : 14.138323,
          lng : 77.314646,
          name:'Pavagada Solar Park', 
          location:' Palavalli, Karnataka' ,
          area : " 13,000 acres",
          capacity:"2,050 MegaWatt" ,
          image_src : 'pavagada' ,
        },
        { 
          id : 1 ,
          lat : 12.876852,
          lng : 78.038313,
           name:'ADANI SOLAR PLANT', 
          location:' Kolar, Karnataka' ,
          area : "2500 Acree ",
          capacity:" 648 MegaWatt " ,
          image_src : 'adani' ,
        },
        { id : 2 ,
            lat : 15.552897,
            lng : 76.431802,
          name:'Karnataka I Project ', 
          location:'Koppal,Karnataka ' ,
          area : " 178 acres",
          capacity:" 40.5 MegaWatt",
          image_src : 'karnataka' ,
        },
        { id : 3 ,
            lat : 12.607107,
            lng : 77.424753,
          name:'Solar power plant', 
          location:'Ramanagara, Karnataka' ,
          area : "92 Acres (approx.)",
          capacity:"20 MegaWatt",
          image_src : 'ramanagara' ,
        },
        { id :4 ,
            lat : 11.965167,
          lng : 76.806878,
          name:'Bosch Power plant ', 
          location:' Chamarajanagar, Karnataka' ,
          area : "1.5 Acres (approx)",
          capacity:"100 KilloWatt",
          image_src : 'ramanagara' ,
        },
  
       ] ; 

       this.googleMapIntialization() ;

    }
 
    googleMapIntialization() {
        this.lat = this.solarPowerPlant[this.urlID].lat ;
        this.lng = this.solarPowerPlant[this.urlID].lng ; 

        // lat = 14.138323;
        // lng = 77.314646;

    this.coordinates = new google.maps.LatLng(this.lat, this.lng);

    const mapOptions: google.maps.MapOptions = {
     center: this.coordinates,
     zoom: 17 ,
     mapTypeId: google.maps.MapTypeId.HYBRID
    };

    this.marker = new google.maps.Marker({
      position: this.coordinates,
      map: this.map,
    }); 

   this.MymapOptions= mapOptions

    }

    title = 'angular-gmap';
    @ViewChild('mapContainer', { static: false }) gmap: ElementRef;
    map: google.maps.Map;
    lat;
    lng ;
    coordinates ;
    marker ;
    MymapOptions
    
    ngAfterViewInit() {
      this.mapInitializer();
    }

    mapInitializer() {
      this.map = new google.maps.Map(this.gmap.nativeElement, 
      this.MymapOptions);
      this.marker.setMap(this.map);
    }
   }



