import { Component, OnInit } from '@angular/core';
import {ActivatedRoute} from '@angular/router' ;
declare const google: any;

interface Marker {
lat: number;
lng: number;
label?: string;
draggable?: boolean;
}
const data = {
    chart: {
      caption: "Power generated by Wind Farm",
      captionontop: "120 MegaWatt",
      origw: "380",
      origh: "250",
      gaugestartangle: "135",
      gaugeendangle: "45",
      gaugeoriginx: "190",
      gaugeoriginy: "220",
      gaugeouterradius: "190",
      theme: "candy",
      showvalue: "1",
      numbersuffix: " %",
      valuefontsize: "25"
    },
    colorrange: {
      color: [
        {
          minvalue: "0",
          maxvalue: "25",
          code: "	#ADD8E6"
        },
        {
          minvalue: "25",
          maxvalue: "50",
          code: "#62B58F "
        },
        {
          minvalue: "50",
          maxvalue: "75",
          code: "#FFC533 "
        }
        , {
            minvalue: "75",
            maxvalue: "100",
            code: "#F2726F"
          }
      ]
    },
    dials: {
      dial: [
        {
          value: "0.3",
          tooltext: "Moderate Pressure"
        }
      ]
    }
  };
@Component({
  selector: 'app-windPlant',
  templateUrl: './windPowerPlant.component.html',
  styleUrls: ['./windPowerPlant.component.css']
})
export class WindPowerPlantComponent implements OnInit {
  
  windPowerPlant
  width = 450;
  height = 400;
  type = "angulargauge";
  dataFormat = "json";
  dataSource = data;
  urlID ;
  constructor(private route : ActivatedRoute ) 
{    
    this.route.params.subscribe(params =>{

        console.log(params['id']) ;
        this.urlID= params['id'] ;
    }) 
}


  ngOnInit() {

    
    this.windPowerPlant =[
        { 
          id : 0 ,
          longitute : 12 ,
          latitute : 13 ,
          name:'Acciona Tuppadahalli', 
          location:'Chitradurga, Karnataka',
          capacity:"56.1 MegaWatt" ,
          image_src : 'pavagada' ,
        },
        { 
          id : 1 ,
          longitute : 12 ,
          latitute : 13 ,
          name:'Shah Gajendragarh MMTCL', 
        	location:' Gadag, Karnataka' ,
        	capacity:" 15 MegaWatt " ,
          image_src : 'adani' ,
        },
        { 
					id : 2 ,
          longitute : 12 ,
          latitute : 13 ,
					name:'Jogmatti BSES ', 
					location:'Chitradurga, Karnataka ' ,
					capacity:" 14 MegaWatt",
          image_src : 'karnataka' ,
        },
        { 
					id : 3 ,
          longitute : 12 ,
          latitute : 13 ,
					name:'Shah Gajendragarh', 
					location:'Gadag, Karnataka' ,
					capacity:"10.8 MegaWatt",
          image_src : 'ramanagara' ,
        },
       ] ;

    var myLatlng = new google.maps.LatLng(40.748817, -73.985428);
    var mapOptions = {
        zoom: 13,
        center: myLatlng,
        scrollwheel: false, 
        styles: [{
            "featureType": "water",
            "stylers": [{
                "saturation": 43
            }, {
                "lightness": -11
            }, {
                "hue": "#0088ff"
            }]
        }, {
            "featureType": "road",
            "elementType": "geometry.fill",
            "stylers": [{
                "hue": "#ff0000"
            }, {
                "saturation": -100
            }, {
                "lightness": 99
            }]
        }, {
            "featureType": "road",
            "elementType": "geometry.stroke",
            "stylers": [{
                "color": "#808080"
            }, {
                "lightness": 54
            }]
        }, {
            "featureType": "landscape.man_made",
            "elementType": "geometry.fill",
            "stylers": [{
                "color": "#ece2d9"
            }]
        }, {
            "featureType": "poi.park",
            "elementType": "geometry.fill",
            "stylers": [{
                "color": "#ccdca1"
            }]
        }, {
            "featureType": "road",
            "elementType": "labels.text.fill",
            "stylers": [{
                "color": "#767676"
            }]
        }, {
            "featureType": "road",
            "elementType": "labels.text.stroke",
            "stylers": [{
                "color": "#ffffff"
            }]
        }, {
            "featureType": "poi",
            "stylers": [{
                "visibility": "off"
            }]
        }, {
            "featureType": "landscape.natural",
            "elementType": "geometry.fill",
            "stylers": [{
                "visibility": "on"
            }, {
                "color": "#b8cb93"
            }]
        }, {
            "featureType": "poi.park",
            "stylers": [{
                "visibility": "on"
            }]
        }, {
            "featureType": "poi.sports_complex",
            "stylers": [{
                "visibility": "on"
            }]
        }, {
            "featureType": "poi.medical",
            "stylers": [{
                "visibility": "on"
            }]
        }, {
            "featureType": "poi.business",
            "stylers": [{
                "visibility": "simplified"
            }]
        }]

    };
    var map = new google.maps.Map(document.getElementById("map"), mapOptions);

    var marker = new google.maps.Marker({
        position: myLatlng,
        title: "Hello World!"
    });

    // To add the marker to the map, call setMap();
    marker.setMap(map);
  }
  



}
